before_install:
  - wget http://algec.iut-blagnac.fr/~jmi/MPA/src/junit.jar
  - "sudo apt-get install graphviz 2>&1 | tail -n 2"
  - wget http://algec.iut-blagnac.fr/~jmi/MPA/src/plantuml.jar
  - hg clone -r 8.6.7 https://asciidoc.googlecode.com/hg/ asciidoc-8.6.7
before_script:
  - wget https://github.com/n1k0/casperjs/archive/1.0.3.tar.gz -O /tmp/casper.tar.gz
  - tar -xvf /tmp/casper.tar.gz
  - export PATH=$PATH:$PWD/casperjs-1.0.3/bin/
language: java
script:
  - java -version
  - javac -version
  - python -V
  - phantomjs -v
  - python asciidoc-8.6.7/asciidoc.py --version
  - dot -V
  - casperjs --version
  - echo Hello from DUT INFO Blagnac
  - ls -alF
  - cd trunk/sprint_5
  - javac -cp ./src:./bin:../../junit.jar -d ./bin ./src/Controller/*.java ./src/Model/*.java ./src/View/*.java ./src/Csv/*.java
  - cd OPTIweb
  - javac -cp .:./bin:../../../junit.jar -d ./bin ./src/MakeOPTIweb.java
  - javac -cp .:./bin:../../../junit.jar -d ./bin ./src/CsvToJson.java
  - javac -cp .:./bin:../../../junit.jar -d ./bin ./src/MakeOPTIwebTest.java
  - cd ..
  - java -jar ../../plantuml.jar -Tpng -o srcdoc/images srcdoc/diag0.puml
  - python ../asciidoc-8.6.7/asciidoc.py -a data-uri -o srcdoc/presentationFinale.html srcdoc/presentationFinale.txt
  - ls -alF srcdoc
  - cd bin
  - java -cp ./ Csv.mainCsv
  - java -cp .:../../../junit.jar:./controller Csv.LibCsvTest
  - cd ../OPTIweb/bin
  - java -cp ./ MakeOPTIweb ../sujets2014_2015.csv ../etudiants2014_2015.csv ../intervenants2014_2015.csv ../projets2014_2015.csv
  - java -cp ./ CsvToJson ../etudiants2014_2015.csv
  - java -cp ./ CsvToJson ../intervenants2014_2015.csv
  - java -cp .:../../../../junit.jar:./ MakeOPTIwebTest
  - cd ../test
  - cp OPTIwebprof.html /tmp/OPTIweb.html
  - casperjs test casperCredits.js
  - casperjs test casperEtudiants.js
  - casperjs test casperIntervenants.js
  - casperjs test casperProjets.js
  - casperjs test casperSujets.js
  - casperjs test casperAccueil.js
  - cd ../..
  - python ../../asciidoc-8.6.7/asciidoc.py -a data-uri -o doc/presentationFinale.html srcdoc/presentationFinale.txt
  - python ../../asciidoc-8.6.7/asciidoc.py -a source-highlighter=pygments -o doc/Documentation_Utilisateur.html srcdoc/Documentation_Utilisateur.txt  
  - python ../../asciidoc-8.6.7/asciidoc.py -a source-highlighter=pygments -o doc/Documentation_Technique.html srcdoc/Documentation_Technique.txt
  - cd OPTIweb
  - python ../../../asciidoc-8.6.7/asciidoc.py -a data-uri -o doc/docTechnique.html srcdoc/docTechnique.txt
  - python ../../../asciidoc-8.6.7/asciidoc.py -a data-uri -o doc/docTechnique_makeOptiWeb.html srcdoc/docTechnique_makeOptiWeb.txt
  - python ../../../asciidoc-8.6.7/asciidoc.py -a data-uri -o doc/docUtilisateur.html srcdoc/docUtilisateur.txt
  - python ../../../asciidoc-8.6.7/asciidoc.py -a data-uri -o doc/docUtilisateur_makeOptiWeb.html srcdoc/docUtilisateur_makeOptiWeb.txt
